apiVersion: v1
kind: Service
metadata:
  name: ssh-np-8-gui
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: nodeport
    nodePort: 30000
    port: 27017
    protocol: TCP
    targetPort: 22
  selector:
    kubevirt.io/domain: devstation-8-gui
  type: NodePort

