apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: devstation-8-hostdisk
spec:
  running: true 
  template:
    metadata:
      labels: 
        kubevirt.io/size: small
        kubevirt.io/domain: devstation-8-hostdisk
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: host-disk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            cpu: 1
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: image-registry.openshift-image-registry.svc:5000/openshift/devstation:v7-terminal
            imagePullPolicy: IfNotPresent
        - name: host-disk
          hostDisk:
            capacity: "1Gi"
            path: /mnt/disk.img
            type: DiskOrCreate
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: | 
              #cloud-config
              users:
                - name: alosadag
                  ssh-authorized-keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu6ebpjHClLxurBN3csEZNbIo3493cqFZGCnpicdeipIWVcU+Hdvy0/CIiZ8AQvcNsaC44zC9PYlHnoFWIfxrGvPvZikUC/qv4xmzNZa60Ype4M3tyMUXlP+vbDu3sOgeIWhyiyvV7NN2DGYF9mi0eKV5u/awS2B/pL6KXPjXjwVZNFB9aur9DkVClgAHc+18pI11RMMuUK4oOPsdopvECgZoWK/zuXrCJQFmqMqlArgveOhGU1FGUpeG63lsf38Xe2+9EXhhcMMuLcYN2BxOwdyRcHt0uflI3SagufUHbBA0vLF4XeTaoU+X2NFM5ToQDdP5Aa+s0mKgGTR9SpknT ansible-generated on eko1.cloud.lab.eng.bos.redhat.com 
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZnG8AIzlDAhpyENpK2qKiTT8EbRWOrz7NXjRzopbPu215mocaJgjjwJjh1cYhgPhpAp6M/ttTk7I4OI7g4588Apx4bwJep6oWTU35LkY8ZxkGVPAJL8kVlTdKQviDv3XX12l4QfnDom4tm4gVbRH0gNT1wzhnLP+LKYm2Ohr9D7p9NBnAdro6k++XWgkDeijLRUTwdEyWunIdW1f8G0Mg8Y1Xzr13BUo3+8aey7HLKJMDtobkz/C8ESYA/f7HJc5FxF0XbapWWovSSDJrr9OmlL9f4TfE+cQk3s+eoKiz2bgNPRgEEwihVbGsCN4grA+RzLCAOpec+2dTJrQvFqsD alosadag@sonnelicht.local 
                  lock_passwd: false
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  groups: users, wheel
